[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM8
monitor_speed = 115200

build_flags =
    -Iinclude
    -Ilib/Ctrl
    -Ilib/Interface
    -Wl,-u,vfscanf
    -lscanf_flt